### ISSUE TITLE
Cannot obtain license

### ISSUE THREAD

**Issue by panjanek** [hybridizer-io/hybridizer-basic-samples#95]
Cannot obtain licence for license ID I got from email:
![image](https://user-images.githubusercontent.com/16365702/99245595-1d362500-2804-11eb-8a61-fbb6db8595f1.png)

Event viewer shows error during service startup:

Cannot create _queryLicenseStatus : Object reference not set to an instance of an object. ::    at hybridizer.developer.service.RegistriesReadWrite.CreateBaseKey()
   at hybridizer.developer.service.RegistriesReadWrite..ctor()
   at hybridizer.developer.service.Service.OnStart(String[] args)

**Comment by enshivam** [comment]
Getting the same issue. Not able to get to even try Hybridizer. @panjanek Were you able to resolve this?

**Comment by donnaken15** [comment]
same here

**Comment by JeWaVe** [comment]
Deeply sorry about that. I'm in a major update process (notably linux/netcore support) and have broken licenses. 
This should work again in the next few weeks.

**Comment by panjanek** [comment]
> Getting the same issue. Not able to get to even try Hybridizer. @panjanek Were you able to resolve this?

Hi. For various reasons I ended up implementing CUDA logic in CUDA C++ and calling native routines from C++ using P/Invoke in C#.

**Comment by JeWaVe** [comment]
Hi. Using CUDAImports (nuget), you have most of CUDA APi already exposed in .Net for P/Invoke
